ALTER TABLE SYMPTOMS
ADD COLUMN PERCENTAGE VARCHAR(10);

UPDATE SYMPTOMS SET PERCENTAGE = 0 
WHERE (TEMP<99);
UPDATE SYMPTOMS SET PERCENTAGE = 20    
WHERE (TEMP>99 AND TEMP<102);      
UPDATE SYMPTOMS SET PERCENTAGE = 40 
WHERE (TEMP>102);
UPDATE SYMPTOMS SET PERCENTAGE = PERCENTAGE + 20 
WHERE    
COUGH='Y' OR RUNNING_NOSE='Y' OR SHORT_BREATH='Y';

UPDATE SYMPTOMS SET PERCENTAGE = PERCENTAGE + 20 
WHERE    
(
(COUGH='Y' AND SHORT_BREATH='Y' ) OR
(COUGH='Y' AND RUNNING_NOSE='Y') OR
(SHORT_BREATH='Y' AND RUNNING_NOSE='Y') 
);
UPDATE SYMPTOMS SET PERCENTAGE = PERCENTAGE + 20 
WHERE    
(
(COUGH='Y' AND SHORT_BREATH='Y' AND RUNNING_NOSE='Y') OR
(COUGH='Y' AND RUNNING_NOSE='Y' AND SHORT_BREATH='Y') OR
(SHORT_BREATH='Y' AND RUNNING_NOSE='Y' AND COUGH='Y') 
);
UPDATE SYMPTOMS SET PERCENTAGE = PERCENTAGE + 10
WHERE (
(FOREIGN_TRP = 'Y')  
);
UPDATE SYMPTOMS SET PERCENTAGE = PERCENTAGE + 10
WHERE (
(PREG = 'Y')  
);
UPDATE SYMPTOMS SET PERCENTAGE = 100 
WHERE PERCENTAGE >= 100;
  
ALTER TABLE ZONE_SELECT
ADD COLUMN PERCENTAGE VARCHAR(10);
UPDATE ZONE_SELECT
SET PERCENTAGE = (
SELECT PERCENTAGE
FROM SYMPTOMS
WHERE SYMPTOMS.USER_ID = ZONE_SELECT.USER_ID
);

UPDATE ZONE_SELECT SET ZONE='G' 
WHERE  PERCENTAGE<20; 
UPDATE ZONE_SELECT SET ZONE='Y' 
WHERE  PERCENTAGE>=20 AND PERCENTAGE<40; 
UPDATE ZONE_SELECT SET ZONE='R' 
WHERE  PERCENTAGE>40; 
UPDATE SUSPECTS
SET ZONE = (
SELECT ZONE
FROM ZONE_SELECT
WHERE SUSPECTS.USER_ID = ZONE_SELECT.USER_ID
);

UPDATE SUSPECTS SET SUSPECT = 'Y' 
WHERE  LOCATION IN (SELECT LOCATION FROM SUSPECTS WHERE ZONE != 'R') = LOCATION IN (SELECT LOCATION FROM ZONE_SELECT WHERE ZONE='R');
UPDATE SUSPECTS SET SUSPECT='N' WHERE SUSPECT = 'Y' AND ZONE = 'R' ;

UPDATE SYMPTOMS
SET PERCENTAGE = CONCAT(PERCENTAGE,' ','%');
UPDATE ZONE_SELECT
SET PERCENTAGE = CONCAT(PERCENTAGE,' ','%');
