	CREATE TABLE BASIC_INFO (
    SR_NO INT(3) AUTO_INCREMENT PRIMARY KEY, 
    USER_ID INT(10) UNIQUE,
    FIRST_NAME VARCHAR(120) NOT NULL ,
    LAST_NAME VARCHAR(120) NOT NULL ,
    GENDER VARCHAR(4) NOT NULL
    );

    CREATE TABLE SYMPTOMS(
    USER_ID INT(10) PRIMARY KEY ,
    TEMP DECIMAL(6,3) NOT NULL ,
    COUGH VARCHAR(1) NOT NULL , 
    SHORT_BREATH VARCHAR(1) NOT NULL ,
    RUNNING_NOSE VARCHAR(1) NOT NULL,
    PREG VARCHAR(1) NOT NULL ,
    FOREIGN_TRP VARCHAR(4) NOT NULL ,
    FOREIGN KEY (USER_ID) REFERENCES BASIC_INFO(USER_ID)
    );

    CREATE TABLE ZONE_SELECT(
    USER_ID INT(10) PRIMARY KEY ,
    ZONE VARCHAR(1) DEFAULT 'G',
    LOCATION VARCHAR(120) NOT NULL ,    
    FOREIGN KEY (USER_ID) REFERENCES BASIC_INFO(USER_ID)
    );

    CREATE TABLE SUSPECTS(
    USER_ID INT(3) PRIMARY KEY,
    LOCATION VARCHAR(120) NOT NULL ,
    ZONE VARCHAR(1) DEFAULT 'G',
    SUSPECT VARCHAR(5) DEFAULT 'N',
    FOREIGN KEY (USER_ID) REFERENCES BASIC_INFO(USER_ID)
    );
