
CREATE TABLE BASIC_INFO (
    SR_NO INT(3) UNIQUE , 
    USER_ID VARCHAR(60) UNIQUE ,
    FIRST_NAME VARCHAR(120) NOT NULL ,
    LAST_NAME VARCHAR(120) NOT NULL ,
    GENDER VARCHAR(4) NOT NULL , 
    FOREIGN_TRP VARCHAR(4) NOT NULL ,
    PREG VARCHAR(1) NOT NULL , 
    LOCATION VARCHAR(120) NOT NULL ,
    TEMP DECIMAL(6,3) NOT NULL ,
    COUGH VARCHAR(1) NOT NULL , 
    SHORT_BREATH VARCHAR(1) NOT NULL ,
    RUNNING_NOSE VARCHAR(1) NOT NULL , 
    COUNT INT(3)  DEFAULT 0, 
    ZONE VARCHAR(1) ,
    AFFECT VARCHAR(1) 
); SELECT * FROM BASIC_INFO;
