CREATE STRUCT (
    SRNO SMALLINT(3) UNIQUE , 
    USER_ID VARCHAR(60) UNIQUE ,
    FIRSTNAME VARCHAR(120) NOT NULL ,
    LASTNAME VARCHAR(120) NOT NULL ,
    GENDER VARCHAR(1) NOT NULL , 
    PREG VARCHAR(1) NOT NULL , 
    IP_ADD VARCHAR(120) UNIQUE ,
    TEMP DECIMAL(6,3) NOT NULL ,
    COUGH VARCHAR(1) NOT NULL , 
    S_BREATH VARCHAR(1) NOT nULL ,
    RUNNY_N VARCHAR(1) NOT NULL ,  
    CATEGORY VARCHAR(1) 
);

