CREATE BASICINFO (
    SRNO SMALLINT(3) UNIQUE , -- WE HAVE TO FIGURE OUT HOW TO INCREAMENT IT WITH EVERY USER ROW.
    USER_ID VARCHAR(60) UNIQUE ,  --THIS FIELD WILL BE USED TO LOGGING IN AS A PERTICULAR USER.
    FIRSTNAME VARCHAR(120) NOT NULL ,
    LASTNAME VARCHAR(120) NOT NULL ,
    GENDER VARCHAR(1) NOT NULL , -- THIS 3 FIELDS ARE HERE JUST TO INCREASE NUMBER OF COLUMNS. WE'VE NOTHNG TO  DO WITH THEM.
    PREG VARCHAR(1) NOT NULL , --IF A LADY IS PREGENANT THERE ARE HIGHER CHANCES OF INFECTION. 
    IP_ADD VARCHAR(120) UNIQUE , -- UNIQUE CONSTAINT FOR LOCATION MATTERS.
    TEMP DECIMAL(6,3) NOT NULL , -- AS PER OUR DISCUSSION . 0 OR 1 OR 2 POINTS TO BE GIVEN (YESS ABHIRAJ 0 | 20 | 40 PERCENT)
    COUGH VARCHAR(1) NOT NULL , -- 0 | 1 POINTS
    S_BREATH VARCHAR(1) NOT nULL ,  -- 0 | 1 POINTS
    RUNNY_N VARCHAR(1) NOT NULL ,  -- 0 | 1 POINTS
    CATEGORY VARCHAR(1) 
);
    -- This is Structure of the Database
