CREATE USER 'ADMIN'@'localhost' IDENTIFIED BY 'StansForLife' ;
CREATE USER 'ORGANISATIONS'@'localhost' IDENTIFIED BY '' ;
CREATE USER 'CLIENTS'@'localhost' IDENTIFIED BY '' ;

-- CREATION OF USERS -- 

GRANT ALL PRIVILEGES ON COVID19DETECT TO 'ADMIN'@'localhost'
GRANT SELECT ON BASIC_INFO TO 'ORGANISATIONS'@'localhost' -- OPERATES AFTER USING A DATABASE -- 
GRANT SELECT ON G_ZONE TO 'CLIENTS'@'localhost' -- OPERATES AFTER USING A DATABASE -- 
GRANT SELECT ON Y_ZONE TO 'CLIENTS'@'localhost' -- OPERATES AFTER USING A DATABASE -- 
GRANT SELECT ON R_ZONE TO 'CLIENTS'@'localhost' -- OPERATES AFTER USING A DATABASE -- 
GRANT SELECT ON A_ZONE TO 'CLIENTS'@'localhost' -- OPERATES AFTER USING A DATABASE -- 


