-- GREEN ZONE
CREATE VIEW G_ZONE AS 
SELECT SR_NO , GENDER , FOREIGN_TRP , PREG , LOCATION , TEMP , COUGH , SHORT_BREATH , RUNNING_NOSE , COUNT , PERCENTAGE 
FROM BASIC_INFO  
WHERE  ZONE = 'G';
-- YELLOW ZONE
CREATE VIEW Y_ZONE AS 
SELECT SR_NO , GENDER , FOREIGN_TRP , PREG , LOCATION , TEMP , COUGH , SHORT_BREATH , RUNNING_NOSE , COUNT , PERCENTAGE 
FROM BASIC_INFO  
WHERE  ZONE = 'Y';
-- RED ZONE
CREATE VIEW R_ZONE AS 
SELECT SR_NO , GENDER , FOREIGN_TRP , PREG , LOCATION , TEMP , COUGH , SHORT_BREATH , RUNNING_NOSE , COUNT , PERCENTAGE 
FROM BASIC_INFO  
WHERE  ZONE = 'R';
-- THE AFFECTED ZONE 
CREATE VIEW A_ZONE AS 
SELECT SR_NO , GENDER , FOREIGN_TRP , PREG , LOCATION , TEMP , COUGH , SHORT_BREATH , RUNNING_NOSE , COUNT , PERCENTAGE 
FROM BASIC_INFO  
WHERE  AFFECT = 'Y' ;
